FROM node:22 AS staging
ENV NODE_ENV=development
WORKDIR /kbbu-web

# Set a higher memory limit for Node.js
ENV NODE_OPTIONS="--max-old-space-size=8192"

# Copy only package.json and yarn.lock first to leverage Docker caching
COPY package.json yarn.lock ./
RUN yarn install --ignore-platform

# Copy the rest of the application files
COPY . /kbbu-web/

# Build the application
# RUN npx update-browserslist-db@latest
RUN yarn run build

# Stage 2: Nginx setup
FROM nginx:latest
WORKDIR /kbbu-web

# Copy the built files from the build stage
COPY --from=staging /kbbu-web /kbbu-web

# Copy the Nginx configuration
COPY --from=staging /kbbu-web/nginx/default.conf /etc/nginx/conf.d/default.conf

# Run Nginx
ENTRYPOINT ["nginx", "-g", "daemon off;"]
EXPOSE 80

# docker build . -t klabbelanjaid/kbbu-web:staging -f Dockerfile.Staging --platform=linux/amd64